window:
  size: [800,600]
  fps: 30

physics:
  gravity: 2
  second: 1000


entities:
  max_vel_x: 10
  max_vel_y: 10
  jump_height: 20

animations:
  leg_climbing_acc: 1
  leg_target: 50
  let_target_height: 50
  keyframes: 10
  animation_paths:
    player:
      walking: "animations/player/walking.json"

models:
  player: "models/player.json"
