logging:
  level: INFO

window:
  size: [960,544]
  maximized: false
  fps: 30

physics:
  gravity: 2
  second: 1000


entities:
  max_vel_x: 15
  max_vel_y: 10
  acc_x: 5
  jump_height: 20

animations:
  leg_climbing_acc: 1
  leg_target: 50
  let_target_height: 50
  animation_speed: 0.3
  animation_paths:
    player:
      idling: "assets/animations/player/idling.json"
      walking: "assets/animations/player/walking.json"

models:
  player: "assets/models/player.json"

maps:
  default_size: [960,544]
  room_rules: "assets/maps/room_rules.json"
  rooms_folder: "assets/maps/rooms/"

debugging:
  map_seed: 18
