logging:
  level: INFO

window:
  size: [960,544]
  maximized: false
  fps: 30

physics:
  gravity: 2
  second: 1000


entities:
  max_vel_x: 10
  max_vel_y: 10
  acc_x: 5
  jump_height: 25

enemies:
  player_detection_ray_size: 200

animations:
  leg_climbing_acc: 1
  leg_target: 50
  let_target_height: 50
  animation_speed: 0.3
  animation_paths:
    player:
      idling: "assets/animations/player/idling.json"
      walking: "assets/animations/player/walking.json"

models:
  player: "assets/models/player.json"
  scale: 0.30

maps:
  room_size: [960,544]
  map_size: 5
  room_rules: "assets/maps/room_rules.json"
  rooms_folder: "assets/maps/rooms/"

sprites:
  room_sprites_folder: "assets/sprites/rooms/"

debugging:
  map_seed: 18
  entity_bbox_color: [0,0,255]
  collider_bbox_color: [255,0,0]
  skeleton_bone_color: [225,240,0]
